apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: covidcurves
spec:
  secretName: covidcurves-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - covidcurves.rossmasters.com
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
